"""Constants for Lambda WP integration."""
DOMAIN = "lambda"
DEFAULT_NAME = "EU08L"
DEFAULT_PORT = 502
DEFAULT_SLAVE_ID = 1
DEFAULT_HOST = "192.168.178.125"

# Konfigurationskonstanten
CONF_SLAVE_ID = "slave_id"

# Debug configuration
DEBUG = False
DEBUG_PREFIX = "lambda_wp"

FIRMWARE_VERSION = {
    "V0.0.3-3K": "1",
    "V0.0.4-3K": "2",
    "V0.0.5-3K": "3",
    "V0.0.6-3K": "4",
    "V0.0.7-3K": "5",
}

# Logging levels
LOG_LEVELS = {
    "error": "ERROR",
    "warning": "WARNING",
    "info": "INFO",
    "debug": "DEBUG"
}

SENSOR_TYPES = {
    # General Ambient
    "aaaadummy": {
        "address": 0,
        "name": "Dummy für FW Selction",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 2,
    },    
    "ambient_error_number": {
        "address": 0,
        "name": "Ambient Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "ambient_operating_state": {
        "address": 1,
        "name": "Ambient Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
    },
    "ambient_temperature": {
        "address": 2,
        "name": "Ambient Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "ambient_temperature_1h": {
        "address": 3,
        "name": "Ambient Temperature 1h",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "ambient_temperature_calculated": {
        "address": 4,
        "name": "Ambient Temperature Calculated",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    # Heat Pump
    "hp1_error_state": {
        "address": 1000,
        "name": "Heat Pump Error State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
    },
    "hp1_error_number": {
        "address": 1001,
        "name": "Heat Pump Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_state": {
        "address": 1002,
        "name": "Heat Pump State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
    },
    "hp1_operating_state": {
        "address": 1003,
        "name": "Heat Pump Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
    },
    "hp1_flow_line_temperature": {
        "address": 1004,
        "name": "Flow Line Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_return_line_temperature": {
        "address": 1005,
        "name": "Return Line Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_volume_flow_heat_sink": {
        "address": 1006,
        "name": "Volume Flow Heat Sink",
        "unit": "l/h",
        "scale": 1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_energy_source_inlet_temperature": {
        "address": 1007,
        "name": "Energy Source Inlet Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_energy_source_outlet_temperature": {
        "address": 1008,
        "name": "Energy Source Outlet Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_volume_flow_energy_source": {
        "address": 1009,
        "name": "Volume Flow Energy Source",
        "unit": "l/min",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_compressor_unit_rating": {
        "address": 1010,
        "name": "Compressor Unit Rating",
        "unit": "%",
        "scale": 0.01,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
    },
    "hp1_actual_heating_capacity": {
        "address": 1011,
        "name": "Actual Heating Capacity",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_inverter_power_consumption": {
        "address": 1012,
        "name": "Inverter Power Consumption",
        "unit": "W",
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_cop": {
        "address": 1013,
        "name": "COP",
        "unit": None,
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_request_type": {
        "address": 1015,
        "name": "Request Type",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_requested_flow_line_temperature": {
        "address": 1016,
        "name": "Requested Flow Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_requested_return_line_temperature": {
        "address": 1017,
        "name": "Requested Return Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_requested_flow_to_return_line_temperature_difference": {
        "address": 1018,
        "name": "Requested Flow to Return Line Temperature Difference",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_relais_state_2nd_heating_stage": {
        "address": 1019,
        "name": "Relais State 2nd Heating Stage",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "hp1_compressor_power_consumption_accumulated": {
        "address": 1020,
        "name": "Compressor Power Consumption Accumulated",
        "unit": "Wh",
        "scale": 1,
        "precision": 0,
        "data_type": "int32",
        "firmware_version": 1,
    },
    "hp1_compressor_thermal_energy_output_accumulated": {
        "address": 1022,
        "name": "Compressor Thermal Energy Output Accumulated",
        "unit": "Wh",
        "scale": 1,
        "precision": 0,
        "data_type": "int32",
        "firmware_version": 1,
    },
    # Boiler
    "boil1_error_number": {
        "address": 2000,
        "name": "Boiler Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
    },
    "boil1_operating_state": {
        "address": 2001,
        "name": "Boiler Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
    },
    "boil1_actual_high_temperature": {
        "address": 2002,
        "name": "Boiler Actual High Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "boil1_actual_low_temperature": {
        "address": 2003,
        "name": "Boiler Actual Low Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "boil1_target_high_temperature": {
        "address": 2050,
        "name": "Boiler Target High Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    # Heating Circuit
    "hc1_error_number": {
        "address": 5000,
        "name": "Heating Circuit Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
    },
    "hc1_operating_state": {
        "address": 5001,
        "name": "Heating Circuit Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
    },
    "hc1_flow_line_temperature": {
        "address": 5002,
        "name": "Flow Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "hc1_return_line_temperature": {
        "address": 5003,
        "name": "Return Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "hc1_room_device_temperature": {
        "address": 5004,
        "name": "Room Device Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "hc1_set_flow_line_temperature": {
        "address": 5005,
        "name": "Set Flow Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "hc1_operating_mode": {
        "address": 5006,
        "name": "Operating Mode",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
    },
    "hc1_set_flow_line_offset_temperature": {
        "address": 5050,
        "name": "Set Flow Line Offset Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "hc1_target_room_temperature": {
        "address": 5051,
        "name": "Target Room Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
    "hc1_set_cooling_mode_room_temperature": {
        "address": 5052,
        "name": "Set Cooling Mode Room Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
    },
}